apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "aws-secrets-synchronizer.clusterRoleName" . }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
