apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aws-secrets-synchronizer.fullname" . }}
  labels:
    {{- include "aws-secrets-synchronizer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "aws-secrets-synchronizer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "aws-secrets-synchronizer.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "aws-secrets-synchronizer.serviceAccountName" . }}
      containers:
        - name: {{ .Values.image.name }}
          image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
