apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
  name: {{ template "aws-secrets-synchronizer.serviceAccountName" . }}
